import type { Lead } from "@/lib/types";
import { daysAgo, daysFromNow, hoursAgo, todayAt } from "./dates";

// A realistic week for a Mumbai/Pune digital agency.
// Mix of stages, sources, owners; several "no website" hot leads.
export const leads: Lead[] = [
  {
    id: "L-101",
    company: "Sharma Sweets & Caterers",
    contactName: "Rakesh Sharma",
    role: "Owner",
    phone: "+91 98191 20301",
    email: "rakesh@sharmasweets.example",
    city: "Mumbai",
    industry: "Food & Catering",
    website: undefined, // no website — hot
    instagram: "@sharmasweets_mumbai",
    stage: "qualified",
    source: "google_maps",
    interest: "combo",
    ownerId: "u-priya",
    score: 88,
    estimatedValue: 85000,
    billingType: "mixed",
    createdAt: daysAgo(9),
    lastActivityAt: daysAgo(2),
    nextActionAt: todayAt(11, 30),
    nextActionNote: "Callback — wants to discuss website + social combo pricing",
    tags: ["hot", "no-website", "festive-season"],
    queueReason: { kind: "callback_due", label: "Callback promised — 11:30 AM today" },
  },
  {
    id: "L-102",
    company: "Green Leaf Ayurveda",
    contactName: "Dr. Meera Iyer",
    role: "Founder",
    phone: "+91 90040 55882",
    email: "meera@greenleaf.example",
    city: "Pune",
    industry: "Healthcare / Wellness",
    website: "greenleafayurveda.example",
    instagram: "@greenleaf.ayurveda",
    stage: "proposal_sent",
    source: "referral",
    interest: "social_media",
    ownerId: "u-priya",
    score: 76,
    estimatedValue: 30000,
    billingType: "retainer",
    createdAt: daysAgo(14),
    lastActivityAt: hoursAgo(3),
    nextActionAt: todayAt(16, 0),
    nextActionNote: "Follow up on Growth proposal — opened it 3 times this morning",
    tags: ["warm", "referral"],
    queueReason: { kind: "proposal_opened", label: "Opened your proposal 3× today" },
  },
  {
    id: "L-103",
    company: "Urban Fitness Studio",
    contactName: "Karan Malhotra",
    role: "Co-founder",
    phone: "+91 99870 33221",
    email: "karan@urbanfit.example",
    city: "Mumbai",
    industry: "Fitness",
    website: "urbanfit.example",
    instagram: "@urbanfit.mumbai",
    stage: "negotiation",
    source: "inbound_website",
    interest: "combo",
    ownerId: "u-priya",
    score: 82,
    estimatedValue: 145000,
    billingType: "mixed",
    createdAt: daysAgo(21),
    lastActivityAt: daysAgo(1),
    nextActionAt: todayAt(15, 0),
    nextActionNote: "Negotiating discount on E-comm + Social Pro bundle",
    tags: ["hot", "high-value"],
    queueReason: { kind: "followup_due", label: "Follow-up due today" },
  },
  {
    id: "L-104",
    company: "Kadam Interiors",
    contactName: "Sunil Kadam",
    role: "Proprietor",
    phone: "+91 98220 77654",
    city: "Pune",
    industry: "Interior Design",
    website: undefined, // no website — hot
    instagram: "@kadam_interiors",
    stage: "new",
    source: "google_maps",
    interest: "website",
    ownerId: "u-priya",
    score: 71,
    estimatedValue: 55000,
    billingType: "one_time",
    createdAt: hoursAgo(4),
    lastActivityAt: hoursAgo(4),
    tags: ["hot", "no-website"],
    queueReason: { kind: "hot_new", label: "Hot new lead — no website, assigned 4h ago" },
  },
  {
    id: "L-105",
    company: "Blossom Play School",
    contactName: "Anita Deshpande",
    role: "Director",
    phone: "+91 91230 44556",
    email: "anita@blossomplay.example",
    city: "Pune",
    industry: "Education",
    website: "blossomplay.example",
    instagram: "@blossomplayschool",
    stage: "contacted",
    source: "manual_research",
    interest: "social_media",
    ownerId: "u-priya",
    score: 58,
    estimatedValue: 30000,
    billingType: "retainer",
    createdAt: daysAgo(18),
    lastActivityAt: daysAgo(13),
    nextActionAt: daysAgo(1),
    nextActionNote: "No contact in 13 days — re-engage before it goes cold",
    tags: ["going-cold"],
    queueReason: { kind: "going_cold", label: "No contact in 13 days" },
  },
  {
    id: "L-106",
    company: "Metro Auto Spares",
    contactName: "Imran Qureshi",
    role: "Owner",
    phone: "+91 98765 11223",
    city: "Mumbai",
    industry: "Automotive",
    website: undefined,
    stage: "new",
    source: "google_maps",
    interest: "website",
    ownerId: "u-priya",
    score: 64,
    estimatedValue: 25000,
    billingType: "one_time",
    createdAt: hoursAgo(20),
    lastActivityAt: hoursAgo(20),
    tags: ["no-website"],
    duplicateOf: { ownerName: "Arjun Nair", lastTouchedAt: daysAgo(40) },
    queueReason: { kind: "hot_new", label: "New lead — assigned yesterday" },
  },
  {
    id: "L-107",
    company: "Coastal Seafood Exports",
    contactName: "Deepak Shetty",
    role: "Director",
    phone: "+91 94480 66778",
    email: "deepak@coastalseafood.example",
    city: "Mangalore",
    industry: "Food Export",
    website: "coastalseafood.example",
    stage: "won",
    source: "referral",
    interest: "combo",
    ownerId: "u-priya",
    score: 95,
    estimatedValue: 175000,
    billingType: "mixed",
    createdAt: daysAgo(35),
    lastActivityAt: daysAgo(3),
    tags: ["won", "high-value"],
  },
  {
    id: "L-108",
    company: "Trendy Threads Boutique",
    contactName: "Pooja Reddy",
    role: "Owner",
    phone: "+91 90000 88991",
    email: "pooja@trendythreads.example",
    city: "Hyderabad",
    industry: "Fashion Retail",
    website: undefined,
    instagram: "@trendythreads.hyd",
    stage: "lost",
    source: "google_maps",
    interest: "social_media",
    ownerId: "u-priya",
    score: 40,
    estimatedValue: 30000,
    billingType: "retainer",
    createdAt: daysAgo(28),
    lastActivityAt: daysAgo(10),
    lostReason: "Went with a freelancer — price sensitive",
    tags: ["lost", "price-sensitive"],
  },
  // ── Other BDAs' leads (visible to admin/manager) ──
  {
    id: "L-201",
    company: "Nair Dental Care",
    contactName: "Dr. Anil Nair",
    role: "Owner",
    phone: "+91 98470 12345",
    email: "anil@nairdental.example",
    city: "Kochi",
    industry: "Healthcare",
    website: "nairdental.example",
    stage: "proposal_sent",
    source: "referral",
    interest: "website",
    ownerId: "u-arjun",
    score: 79,
    estimatedValue: 55000,
    billingType: "one_time",
    createdAt: daysAgo(12),
    lastActivityAt: daysAgo(2),
    nextActionAt: daysFromNow(1),
    tags: ["warm"],
  },
  {
    id: "L-202",
    company: "Spice Route Restaurant",
    contactName: "Vikram Menon",
    role: "Partner",
    phone: "+91 98460 55667",
    city: "Kochi",
    industry: "Hospitality",
    website: undefined,
    instagram: "@spiceroute.kochi",
    stage: "qualified",
    source: "google_maps",
    interest: "combo",
    ownerId: "u-arjun",
    score: 84,
    estimatedValue: 95000,
    billingType: "mixed",
    createdAt: daysAgo(8),
    lastActivityAt: daysAgo(4),
    nextActionAt: daysAgo(2), // overdue — leakage signal
    tags: ["hot", "no-website", "sla-breach"],
  },
  {
    id: "L-203",
    company: "TechEdge Coaching",
    contactName: "Ramesh Gupta",
    role: "Director",
    phone: "+91 99001 22334",
    email: "ramesh@techedge.example",
    city: "Bengaluru",
    industry: "Education",
    website: "techedge.example",
    stage: "new",
    source: "inbound_website",
    interest: "outreach",
    ownerId: "u-arjun",
    score: 60,
    estimatedValue: 40000,
    billingType: "retainer",
    createdAt: daysAgo(3), // untouched for 3 days — leakage
    lastActivityAt: daysAgo(3),
    tags: ["untouched", "sla-breach"],
  },
  {
    id: "L-301",
    company: "Sunrise Builders",
    contactName: "Prakash Rao",
    role: "MD",
    phone: "+91 96860 44556",
    email: "prakash@sunrisebuilders.example",
    city: "Chennai",
    industry: "Real Estate",
    website: "sunrisebuilders.example",
    stage: "negotiation",
    source: "referral",
    interest: "combo",
    ownerId: "u-fatima",
    score: 87,
    estimatedValue: 210000,
    billingType: "mixed",
    createdAt: daysAgo(25),
    lastActivityAt: daysAgo(1),
    nextActionAt: daysFromNow(2),
    tags: ["hot", "high-value"],
  },
  {
    id: "L-302",
    company: "Lakshmi Textiles",
    contactName: "Geetha Subramanian",
    role: "Owner",
    phone: "+91 94440 77889",
    city: "Coimbatore",
    industry: "Textile",
    website: undefined,
    stage: "won",
    source: "google_maps",
    interest: "website",
    ownerId: "u-fatima",
    score: 90,
    estimatedValue: 55000,
    billingType: "one_time",
    createdAt: daysAgo(30),
    lastActivityAt: daysAgo(5),
    tags: ["won"],
  },
  {
    id: "L-303",
    company: "Bay View Resorts",
    contactName: "Thomas Kurian",
    role: "GM",
    phone: "+91 98950 33445",
    email: "thomas@bayview.example",
    city: "Goa",
    industry: "Hospitality",
    website: "bayview.example",
    instagram: "@bayviewresorts",
    stage: "contacted",
    source: "manual_research",
    interest: "social_media",
    ownerId: "u-fatima",
    score: 68,
    estimatedValue: 55000,
    billingType: "retainer",
    createdAt: daysAgo(6),
    lastActivityAt: daysAgo(2),
    nextActionAt: daysFromNow(1),
    tags: ["warm"],
  },

  // ── Explore pool — unclaimed leads any BDA can acquire ──
  {
    id: "L-901",
    company: "Kumar Electronics",
    contactName: "Suresh Kumar",
    role: "Owner",
    phone: "+91 98330 71120",
    email: "suresh@kumarelectronics.example",
    city: "Mumbai",
    industry: "Retail / Electronics",
    website: undefined,
    stage: "new",
    source: "google_maps",
    interest: "website",
    ownerId: "",
    score: 72,
    estimatedValue: 45000,
    billingType: "one_time",
    createdAt: daysAgo(3),
    lastActivityAt: daysAgo(3),
    tags: ["no-website"],
    pooled: true,
    pooledAt: daysAgo(3),
  },
  {
    id: "L-902",
    company: "Spice Route Restaurant",
    contactName: "Anjali Menon",
    role: "Partner",
    phone: "+91 90210 44556",
    email: "anjali@spiceroute.example",
    city: "Kochi",
    industry: "Food & Beverage",
    website: undefined,
    instagram: "@spiceroute.kochi",
    stage: "new",
    source: "manual_research",
    interest: "social_media",
    ownerId: "",
    score: 65,
    estimatedValue: 30000,
    billingType: "retainer",
    createdAt: daysAgo(5),
    lastActivityAt: daysAgo(5),
    tags: ["no-website"],
    pooled: true,
    pooledAt: daysAgo(5),
  },
  {
    id: "L-903",
    company: "Peak Fitness Gym",
    contactName: "Rohit Deshpande",
    role: "Owner",
    phone: "+91 98220 99001",
    email: "rohit@peakfitness.example",
    city: "Pune",
    industry: "Fitness",
    website: "peakfitness.example",
    stage: "contacted",
    source: "indiamart",
    interest: "combo",
    ownerId: "",
    score: 58,
    estimatedValue: 60000,
    billingType: "mixed",
    createdAt: daysAgo(12),
    lastActivityAt: daysAgo(8),
    tags: ["cold"],
    pooled: true,
    pooledBy: "u-arjun",
    pooledAt: daysAgo(4),
    pooledNote: "Out of my region — releasing for anyone in Pune to pick up.",
  },
  {
    id: "L-904",
    company: "Little Steps Playschool",
    contactName: "Fatima Rizvi",
    role: "Director",
    phone: "+91 99870 22334",
    email: "hello@littlesteps.example",
    city: "Mumbai",
    industry: "Education",
    website: undefined,
    stage: "new",
    source: "referral",
    interest: "website",
    ownerId: "",
    score: 70,
    estimatedValue: 35000,
    billingType: "one_time",
    createdAt: daysAgo(2),
    lastActivityAt: daysAgo(2),
    tags: ["no-website", "referral"],
    pooled: true,
    pooledAt: daysAgo(2),
  },
];

export function leadById(id: string) {
  return leads.find((l) => l.id === id);
}
