import type { User, Team, ServicePackage, SalaryStructure, LeaveBalance } from "@/lib/types";
import { daysAgo } from "@/lib/seed/dates";

export const teams: Team[] = [
  { id: "team-1", name: "West Sales" },
  { id: "team-2", name: "South Sales" },
];

// monthly salary split into components
function sal(monthly: number): SalaryStructure {
  const basic = Math.round(monthly * 0.5);
  const hra = Math.round(monthly * 0.2);
  return { basic, hra, special: monthly - basic - hra };
}
const bal = (casual: number, sick: number, earned: number): LeaveBalance => ({ casual, sick, earned });

export const users: User[] = [
  {
    id: "u-admin",
    name: "Rohan Mehta",
    email: "rohan@pixelforge.in",
    role: "admin",
    accessLevel: "admin",
    departmentId: "dept-admin",
    designation: "Founder & Director",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(1400),
    location: "Mumbai",
    phone: "+91 98200 11111",
    ctcAnnual: 3600000,
    salary: sal(300000),
    bankLast4: "6721",
    leaveBalance: bal(12, 8, 20),
  },
  {
    id: "u-mgr",
    name: "Sneha Kulkarni",
    email: "sneha@pixelforge.in",
    role: "manager",
    accessLevel: "manager",
    departmentId: "dept-bda",
    designation: "Sales Manager",
    managerId: "u-admin",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(900),
    location: "Mumbai",
    phone: "+91 98200 22222",
    teamId: "team-1",
    ctcAnnual: 1800000,
    salary: sal(150000),
    bankLast4: "4410",
    leaveBalance: bal(9, 6, 14),
  },
  {
    id: "u-priya",
    name: "Priya Sharma",
    email: "priya@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-bda",
    designation: "Senior BDA",
    managerId: "u-mgr",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(520),
    location: "Mumbai",
    phone: "+91 98200 33333",
    teamId: "team-1",
    monthlyTargetCalls: 400,
    monthlyTargetRevenue: 500000,
    ctcAnnual: 780000,
    salary: sal(65000),
    bankLast4: "9032",
    leaveBalance: bal(6, 4, 9),
  },
  {
    id: "u-arjun",
    name: "Arjun Nair",
    email: "arjun@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-bda",
    designation: "BDA",
    managerId: "u-mgr",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(300),
    location: "Mumbai",
    phone: "+91 98200 44444",
    teamId: "team-1",
    monthlyTargetCalls: 400,
    monthlyTargetRevenue: 500000,
    ctcAnnual: 600000,
    salary: sal(50000),
    bankLast4: "1187",
    leaveBalance: bal(8, 5, 6),
  },
  {
    id: "u-fatima",
    name: "Fatima Sheikh",
    email: "fatima@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-bda",
    designation: "BDA",
    managerId: "u-mgr",
    status: "on_leave",
    employmentType: "full_time",
    joinedAt: daysAgo(240),
    location: "Pune",
    phone: "+91 98200 55555",
    teamId: "team-2",
    monthlyTargetCalls: 400,
    monthlyTargetRevenue: 450000,
    ctcAnnual: 600000,
    salary: sal(50000),
    bankLast4: "7788",
    leaveBalance: bal(3, 4, 5),
  },

  // ── Technology ──
  {
    id: "u-vikram",
    name: "Vikram Rao",
    email: "vikram@pixelforge.in",
    role: "manager",
    accessLevel: "manager",
    departmentId: "dept-tech",
    designation: "Engineering Manager",
    managerId: "u-admin",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(1050),
    location: "Bengaluru",
    phone: "+91 98200 66661",
    ctcAnnual: 2400000,
    salary: sal(200000),
    bankLast4: "3355",
    leaveBalance: bal(10, 7, 16),
  },
  {
    id: "u-aditya",
    name: "Aditya Verma",
    email: "aditya@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-tech",
    designation: "Full-stack Engineer",
    managerId: "u-vikram",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(460),
    location: "Bengaluru",
    phone: "+91 98200 66662",
    ctcAnnual: 1200000,
    salary: sal(100000),
    bankLast4: "2201",
    leaveBalance: bal(7, 5, 11),
  },
  {
    id: "u-neha",
    name: "Neha Gupta",
    email: "neha@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-tech",
    designation: "Frontend Engineer",
    managerId: "u-vikram",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(210),
    location: "Remote",
    phone: "+91 98200 66663",
    ctcAnnual: 960000,
    salary: sal(80000),
    bankLast4: "5540",
    leaveBalance: bal(9, 6, 4),
  },
  {
    id: "u-karan",
    name: "Karan Singh",
    email: "karan@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-tech",
    designation: "Backend Engineer (Intern)",
    managerId: "u-vikram",
    status: "active",
    employmentType: "intern",
    joinedAt: daysAgo(75),
    location: "Bengaluru",
    phone: "+91 98200 66664",
    ctcAnnual: 300000,
    salary: sal(25000),
    bankLast4: "8899",
    leaveBalance: bal(4, 3, 0),
  },

  // ── Media & Marketing ──
  {
    id: "u-ananya",
    name: "Ananya Iyer",
    email: "ananya@pixelforge.in",
    role: "manager",
    accessLevel: "manager",
    departmentId: "dept-media",
    designation: "Marketing Lead",
    managerId: "u-admin",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(680),
    location: "Mumbai",
    phone: "+91 98200 77771",
    ctcAnnual: 1500000,
    salary: sal(125000),
    bankLast4: "6612",
    leaveBalance: bal(8, 7, 12),
  },
  {
    id: "u-rahul",
    name: "Rahul Desai",
    email: "rahul@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-media",
    designation: "Content Strategist",
    managerId: "u-ananya",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(330),
    location: "Mumbai",
    phone: "+91 98200 77772",
    ctcAnnual: 720000,
    salary: sal(60000),
    bankLast4: "3390",
    leaveBalance: bal(6, 5, 7),
  },
  {
    id: "u-isha",
    name: "Isha Kapoor",
    email: "isha@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-media",
    designation: "Performance Marketer",
    managerId: "u-ananya",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(150),
    location: "Remote",
    phone: "+91 98200 77773",
    ctcAnnual: 840000,
    salary: sal(70000),
    bankLast4: "4471",
    leaveBalance: bal(9, 6, 5),
  },

  // ── People & Ops ──
  {
    id: "u-meera",
    name: "Meera Joshi",
    email: "meera@pixelforge.in",
    role: "bda",
    accessLevel: "employee",
    departmentId: "dept-admin",
    designation: "HR & Ops Executive",
    managerId: "u-admin",
    status: "active",
    employmentType: "full_time",
    joinedAt: daysAgo(400),
    location: "Mumbai",
    phone: "+91 98200 88881",
    ctcAnnual: 660000,
    salary: sal(55000),
    bankLast4: "1029",
    leaveBalance: bal(10, 8, 9),
  },
];

export const CURRENT_BDA_ID = "u-priya";
export const CURRENT_ADMIN_ID = "u-admin";

export function userById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function userName(id: string): string {
  return userById(id)?.name ?? "Unknown";
}

export function usersByDept(departmentId: string): User[] {
  return users.filter((u) => u.departmentId === departmentId);
}

/** direct + indirect reports of a manager (their subtree) */
export function reportsOf(managerId: string): User[] {
  const direct = users.filter((u) => u.managerId === managerId);
  return direct.flatMap((u) => [u, ...reportsOf(u.id)]);
}

// ── Service catalogue — what a digital agency actually sells ──
export const servicePackages: ServicePackage[] = [
  {
    id: "pkg-smm-starter",
    category: "social_media",
    name: "Social — Starter",
    tagline: "Consistent presence for a single platform",
    sacCode: "998361",
    gstRate: 18,
    billingType: "retainer",
    price: 15000,
    deliverables: ["12 feed posts / month", "1 platform (Instagram)", "Basic captions & hashtags", "Monthly report"],
    timelineDays: 30,
    revisions: 1,
  },
  {
    id: "pkg-smm-growth",
    category: "social_media",
    name: "Social — Growth",
    tagline: "Multi-platform content with reels",
    sacCode: "998361",
    gstRate: 18,
    billingType: "retainer",
    price: 30000,
    deliverables: ["16 feed posts / month", "8 reels / month", "2 platforms", "Story designs", "Bi-weekly report"],
    timelineDays: 30,
    revisions: 2,
  },
  {
    id: "pkg-smm-pro",
    category: "social_media",
    name: "Social — Pro",
    tagline: "Full-service social with ads management",
    sacCode: "998361",
    gstRate: 18,
    billingType: "retainer",
    price: 55000,
    deliverables: ["24 posts / month", "12 reels / month", "3 platforms", "Ad campaign management", "Influencer coordination", "Weekly report"],
    timelineDays: 30,
    revisions: 3,
  },
  {
    id: "pkg-web-landing",
    category: "website",
    name: "Website — Landing Page",
    tagline: "High-converting single page",
    sacCode: "998314",
    gstRate: 18,
    billingType: "one_time",
    price: 25000,
    deliverables: ["1 responsive landing page", "Contact form", "Basic SEO", "1 year hosting"],
    timelineDays: 10,
    revisions: 2,
  },
  {
    id: "pkg-web-5page",
    category: "website",
    name: "Website — 5 Page",
    tagline: "Complete business website",
    sacCode: "998314",
    gstRate: 18,
    billingType: "one_time",
    price: 55000,
    deliverables: ["5 responsive pages", "CMS setup", "Contact + enquiry forms", "On-page SEO", "1 year hosting + SSL"],
    timelineDays: 21,
    revisions: 3,
  },
  {
    id: "pkg-web-ecom",
    category: "website",
    name: "Website — E-commerce",
    tagline: "Online store with payments",
    sacCode: "998314",
    gstRate: 18,
    billingType: "one_time",
    price: 120000,
    deliverables: ["Product catalogue", "Payment gateway", "Order management", "Up to 100 products", "SEO + analytics"],
    timelineDays: 45,
    revisions: 3,
  },
  {
    id: "pkg-out-setup",
    category: "outreach",
    name: "Outreach — Lead Gen",
    tagline: "Cold outreach & appointment setting",
    sacCode: "998599",
    gstRate: 18,
    billingType: "retainer",
    price: 40000,
    deliverables: ["Prospect list building", "Email + LinkedIn sequences", "40 qualified leads / month", "Weekly pipeline report"],
    timelineDays: 30,
    revisions: 0,
  },
  {
    id: "pkg-web-amc",
    category: "website",
    name: "Website — Maintenance (AMC)",
    tagline: "Ongoing updates & support",
    sacCode: "998314",
    gstRate: 18,
    billingType: "retainer",
    price: 8000,
    deliverables: ["Monthly updates", "Security patches", "Uptime monitoring", "2 hrs content changes"],
    timelineDays: 30,
    revisions: 0,
  },
];

export function packageById(id: string) {
  return servicePackages.find((p) => p.id === id);
}
